export const QRCODE_LIST_REQUEST = "QRCODE_LIST_REQUEST";
export const QRCODE_LIST_SUCCESS = "QRCODE_LIST_SUCCESS";
export const QRCODE_LIST_FAIL = "QRCODE_LIST_FAIL";

export const QRCODE_CREATE_REQUEST = "QRCODE_CREATE_REQUEST";
export const QRCODE_CREATE_SUCCESS = "QRCODE_CREATE_SUCCESS";
export const QRCODE_CREATE_FAIL = "QRCODE_CREATE_FAIL";
export const QRCODE_CREATE_RESET = "QRCODE_CREATE_RESET";

export const QRCODE_UPDATE_REQUEST = "QRCODE_UPDATE_REQUEST";
export const QRCODE_UPDATE_SUCCESS = "QRCODE_UPDATE_SUCCESS";
export const QRCODE_UPDATE_FAIL = "QRCODE_UPDATE_FAIL";
export const QRCODE_UPDATE_RESET = "QRCODE_UPDATE_RESET";
