export const EventType = {
  SCANNED_AT_POS: "Scan at refill machine",
  FILLED: "Filled",
  FILLED_ON_PREMISES: "Fill",
  SCANNED_AT_POR: "Scan at return station",
  SCANNED_AT_SMARTTRACK: "Scan from smarttrack",
  SCANNED_AT_REVOWEB: "Scan at revo web",
  SCANNED_AT_REVOAPP: "Scan at revo app",
  WEBSITE_LEAD_GENERATION: "Scan to navigate to website",
  PREFILLED: "Prefilled",
  REFILLED: "Refilled",
  RETURNED: "Returned",
  SELF_ASSIGNMENT_BY_CUSTOMER: "Customer Self Assignment",
  SELF_UNASSIGNMENT_BY_CUSTOMER: "Customer Self Unassignment",
  FILL_AFTER_RETURN: "Fill after retrun",
  ARCHIVED: "Archived",
  LOST: "Lost",
  CLEANING: "Cleaning",
  SHIPPING: "Shiping",
};
